### ISSUE TITLE
порт gcc stm32f1xx - некорректная инициализация flash

### ISSUE THREAD

**Issue by esaulenka** [scmrtos/scmrtos-sample-projects#1]
scmrtos-sample-projects/samples/cortex/mx-gcc/common/stm32/f1xx/sysinit.cpp

```
// Flash 2 wait state (if freq in 24..48 MHz range - 1WS.)
FLASH->ACR = (FLASH->ACR & ~FLASH_ACR_LATENCY) | FLASH_ACR_LATENCY_2;
```

комментарий правильный, однако
FLASH_ACR_LATENCY_2 - это установка бита 2, т.е., вероятно, 4 wait state'а (не знаю, поддерживается ли... проверять быстродействие поленился).

Корректный код должен выставлять первый бит:
```
// Flash 2 wait state (if freq in 24..48 MHz range - 1WS.)
FLASH->ACR = (FLASH->ACR & ~FLASH_ACR_LATENCY) | FLASH_ACR_LATENCY_1;
```

Для остальных камней ошибки вроде б нет.
Спасибо ST'шникам за простые и понятные заголовки, чтоб их...

**Comment by antongus** [comment]
[FLASH_ACR_LATENCY_2](https://github.com/scmrtos/scmrtos-sample-projects/blob/master/samples/cortex/mx-gcc/common/CMSIS/stm32/stm32f10x.h#L7680) - это не второй бит, это просто 2 :)

**Comment by esaulenka** [comment]
действительно, самдурак.
Прошу прощения за преждевременную панику.

**Comment by antongus** [comment]
Да уж, зоопарк какой-то. Неужели им трудно было добавить в название конкретики:

    FLASH_ACR_LATENCY_2_WS
или

    FLASH_ACR_LATENCY_BIT_2
? Впрочем, это риторический вопрос :)
