### ISSUE TITLE
scmrtos on msp430g2553?

### ISSUE THREAD

**Issue by vitasam** [scmrtos/scmrtos-sample-projects#2]
Hi,
will it work on msp430g2553?

**Comment by antongus** [comment]
Hi!
Unfortunately, authors of MSP430 ports does not use newer MSP430 chips.
Here you can find sample projects for MSP430F149(GCC and IAR) and MSP430F2617 (IAR). If your chip is similar to one of this, you can try to adopt one of this projects.

**Comment by vitasam** [comment]
Hi,
thank you! Just double checked from datasheets - **msp430f149** is more powerful MCU (60KB+256B Flash Memory, 2KB RAM) vs **msp430g2553** (16KB Flash Memory + 512B RAM).

In theory it should be possible to port, as far as I understood.
