### ISSUE TITLE
Serial.print

### ISSUE THREAD

**Issue by dvv** [scmrtos/scmrtos-sample-projects#4]
Тестовый код для platformio для maple board (stm32f103c8t6).

```cpp
#include <Arduino.h>
#include <scmRTOS.h>
#if scmRTOS_IDLE_HOOK_ENABLE
void OS::idle_process_user_hook() { loop(); }
#endif

void setup() {
  Serial.begin(115200);
  // start OS
  // UNLOCK_SYSTEM_TIMER();
  // OS::run();
}

void loop() {
  Serial.print("-");
}

//------------------------------------------------------------------------------

typedef OS::process<OS::pr0, 256> TProc0;
static TProc0 Proc0;

namespace OS
{
  template<> OS_PROCESS void TProc0::exec() {
    for (;;) {
      Serial.print("+");
      OS::sleep(1000);
    }
  }
}
```

Печатаются минусы в `/dev/ttyACM0`.
После включения OS (раскомментировать в `setup`), `/dev/ttyACM0` пропадает.

Очевидно какой-то стык в использовании системного таймера scmRTOS и stm32duino.
Прямое заимствование из [здешнего примера](https://github.com/scmrtos/scmrtos-sample-projects/tree/master/samples/cortex/mx-gcc/6-custom-timer-m3-stm32f1xx) не прошло -- отсутствуют определения уже в `RCC->APB1ENR |= RCC_APB1ENR_TIM4EN;`.

Подскажите пож, как пофиксить?

**Comment by antongus** [comment]
TIM4 в stm32f103c8t6 есть. Возможно, надо просто подключить нужный заголовочный файл:
`#include "stm32f10x.h"`
?
Ну и замечание заодно: если будете печатать в Serial из разных процессов, то желательно обернуть запись в мьютексы. Потому что вряд ли ардуиновский Serial рассчитан на многопоточность.

**Comment by dvv** [comment]
Дело в том, что такого заголовочного файла нет. Могли бы вы создать тут пример с выводом в USBSerial на базе [stm32duino](https://github.com/stm32duino/Arduino_Core_STM32)?
Спасибо

**Comment by antongus** [comment]
Вы свой проект сюда приложите, (или куда удобнее), я посмотрю.

Ну и замечание в сторону: "не помогает", "не работает" - не очень информативные описания проблемы. Гораздо полезнее: "компилятор ругается на...", "текст ошибки: ..." :)

**Comment by antongus** [comment]
Что касаемо PendSVC_ISR - это староне название, его сейчас убрали отовсюду.
Сейчас это прерывание занывается  PendSV_Handler. 
Попробуйте в os_target.cpp добавить эту строчку
`#pragma weak __exc_pendsv = PendSV_Handler`

**Comment by dvv** [comment]
> Вы свой проект сюда приложите, (или куда удобнее), я посмотрю.

[Готово](https://github.com/dvv/scmrtos-test0).
[Platformio тут](https://docs.platformio.org/en/latest/installation.html).

Спасибо!

**Comment by antongus** [comment]
Поставил platformio (в виде плагина к vs code), заморгал светодиодиком (у меня плата STM32MINI, с алиэкспресс). Ну, думаю, успех близко. Но не тут то было...

Пытаюсь подцепить `scmrtos` - не выходит каменный цветок. Сначала не компилировалось - я пытался файлы настройки оси положить в директорию src, а такого сценария не предусмотрено. Хорошо, положил в lib/scmrtos, хотя это и не правильно. 
Теперь компилируется, но не работает. Как только я пытаюсь задействовать что-то из библиотеки ардуино, сразу компилироваться перестаёт - вылезает ошибка многократного определения функции `TIM4_IRQHandler`. Оказывается, библиотека ардуины внутри себя определяет все эти вектора, и для их использования надо вызывать какие-то спец. функции. 
Но это не самое главное. Я дизасемблировал результирующий elf, и там нет функции `__exc_pendsv`. Почему-то не цепляет. Возможно потому, что она в ассемблерном файле.
В общем, дальше надо копать очень глубоко, а мой выходной закончился :)
(Вот поэтому не люблю такие комбайны автоматизированные - пока всё работает, они прекрасны. А как только что-то идёт не так, как задумали авторы комбайна, так всё, туши свет. Механизма поправить дело или нет, или он закопан глубоко-глубоко).

**Comment by antongus** [comment]
Только пожаловался - заработало:)
Взял версию scmrtos, в которой обработчик PendSV в cpp файле, отключил custom таймер (с ним почему-то не работает, возможно ардуиновская либа его как-то перенастраивает), вернул SysTick - заработало. По крайней мере, светодиодик мигает из задачи. Остальное не знаю. Где искать выхлоп от Serial.print() - не знаю. USB не энумерируется, в аппаратном USART - тихо. 
Короче, вот, прикладываю то, что у меня получилось. Если будет развитие - пишите сюда.
[test1.zip](https://github.com/scmrtos/scmrtos-sample-projects/files/2800488/test1.zip)

**Comment by antongus** [comment]
Во, задышал serial. Я заменил Serial на Serial1, и появились импульсы на PA9. Добавил передачу управления между процессами - работает. В общем, вот: [test2.zip](https://github.com/scmrtos/scmrtos-sample-projects/files/2800563/test2.zip). Надеюсь, поможет.
(USB-CDC для bluepill и для моего клона не поддерживается, как я понял).

**Comment by dvv** [comment]
Ага, спасибо! Поправилось (у меня плата со светодиодом на PB1), собралось, залилось, но не замигало (
До-scmrtos-ные проекты собирал с учетом [таких определений](https://github.com/dvv/scmrtos-test0/blob/master/platformio.ini#L22-L24) -- там всё хозяйство на основе `libmaple` и USBSerial (`Serial`) рабочий.
Очевидно, разные варианты из определений BLUEPILL_F103C8 vs. stm32f1 многое делают по разному.

**Comment by antongus** [comment]
Думаю, что надо всё же допилить custom таймер. Видимо, systick где-то ещё используется в недрах библиотек. Типа, тайм-ауты отрабатываются и всё такое.
Надо просто следовать их правилам, зацепить обработчик таймерного прерывания через
TimerHandleInit(),  attachIntHandle().

**Comment by dvv** [comment]
В моей плате зацеплял обработчик [сюда](https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/cores/maple/libmaple/systick.c#L86).

**Comment by dvv** [comment]
Успех! (USBSerial и моргалка)[https://github.com/dvv/scmrtos-test0].
Спасибо!
